[versions]
agp = "8.13.2"
kotlin = "2.2.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.08.00"
material3 = "1.3.2"
retrofit = "3.0.0"
coil = "3.3.0"
hilt = "2.56.2"
hiltCompose = "1.2.0"
okhttp = "4.9.3"
ksp = "2.2.0-2.0.2"
moshi = "1.15.2"
composeMaterial3 = "1.5.6"
mockk = "1.14.5"
kotlinx-coroutines = "1.9.0"
junit5Bom = "5.13.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

#Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitMoshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

#Moshi
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshiAdapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshiCodegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

#Coil
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

#Hilt
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltCompose" }

#Compose
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-fixed-version = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "composeMaterial3" }

#Testing
junit5-bom = { module = "org.junit:junit-bom", version.ref = "junit5Bom" }
junit5-kotlin = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
junit5-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit5-engine-jupiter = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit5-engine-vintage = { module = "org.junit.vintage:junit-vintage-engine" }
junit5-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
coil = [
    "coil-compose",
    "coil-network-okhttp",
]

retrofit = [
    "retrofit",
    "retrofitMoshi",
    "okhttp-logging-interceptor"
]

hilt = [
    "hilt",
    "hilt-compose"
]

compose = [
    "androidx-compose-material3",
    "androidx-compose-material3-fixed-version",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview",
]

junit5Test = [
    "junit5-kotlin",
    "junit5-jupiter",
    "junit5-api",
    "junit5-params",
]

junit5Runtime = [
    "junit5-engine-jupiter",
    "junit5-engine-vintage",
    "junit5-platform-launcher",
]


